# Generated by Django 4.0.6 on 2022-07-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='display_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
