# Generated by Django 4.0.6 on 2022-07-07 06:31

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_object_display_date'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='object',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='extra_attributes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
